### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by pbiggar** [zeeshanadnan/free-palestine-banner#1]
Hey, I wanted to suggest this to people to use, as it's the only library like it. However, some issues:

- I'm not sure where it goes when it installs - a screenshot of a page using it would be helpful
- We added a #FreePalestine banner to darklang.com, and an important part was a link to our founder's statement on the subject. So it would be good if it was easy to add a link to something (maybe even suggest one)
- it looks a bit weird. I'm not a designer so im not sure how to express the problem, but it looks "off" maybe?
- a JS library is good, and since you have the image you could also just provide template html so that people could add it to their sites, if their site doesn't use the JS lib.

Hope this is helpful.

**Comment by zeeshanadnan** [comment]
Hi @pbiggar firstly thanks for all the suggestions. I designed this keeping in mind that i want it to be very minimum steps to setup. You can just import the script and good to go.

- I revamped the whole design keeping your suggestions in mind. Found the banner at bottom or top to be more UX friendly rather than the floating one which i designed previously. I took inspiration from the darklang site.  Added preview with a reference site.
- Added option to add link and custom statement in the banner.
- I agree. I am also not a designer my self. But putting it in some site showed that it did not look very good overall.
- I kept is a simple JS lib as it is. I would recommend [support-palestine-banner](https://github.com/Safouene1/support-palestine-banner) for setting up with html and css . My goal was to very minimum setup.

I reference your article in the README file. Hope you are ok with it.

**Comment by pbiggar** [comment]
Yes, no problem!

Fyi, we're working on some related things. Could you reach out to my via email? Paul.biggar@gmail.com
